<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pnbp_model extends CI_Model
{

    public $table = 'm_pnbp';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('nik', $q);
	$this->db->or_like('nama_polres', $q);
	$this->db->or_like('kota', $q);
	$this->db->or_like('polda', $q);
	$this->db->or_like('provinsi', $q);
	$this->db->or_like('samsat', $q);
	$this->db->or_like('loket', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('surat', $q);
	$this->db->or_like('transaksi', $q);
	$this->db->or_like('jenis', $q);
	$this->db->or_like('harga', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('nik', $q);
	$this->db->or_like('nama_polres', $q);
	$this->db->or_like('kota', $q);
	$this->db->or_like('polda', $q);
	$this->db->or_like('provinsi', $q);
	$this->db->or_like('samsat', $q);
	$this->db->or_like('loket', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('surat', $q);
	$this->db->or_like('transaksi', $q);
	$this->db->or_like('jenis', $q);
	$this->db->or_like('harga', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pnbp_model.php */
/* Location: ./application/models/Pnbp_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-08-08 18:39:09 */
/* http://harviacode.com */