<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_kunjungan_model extends CI_Model
{

    public $table = 't_kunjungan';
    public $id = 'idkunjungan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get all dash
    function get_all_dash()
    {
        //$this->db->order_by($this->id, $this->order);
        //return $this->db->get($this->table)->result();
        $this->db->select('a.idkunjungan, SUM(a.rj) AS rj, SUM(a.ri) AS ri,SUM(a.igd) AS igd,b.nm_rs');
        $this->db->from('t_kunjungan a');
        $this->db->join('m_rs b', 'b.kdrs = a.kdrs', 'left');
        $this->db->group_by('a.kdrs');
        $query = $this->db->get();
        return $query->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('idkunjungan', $q);
        $this->db->or_like('kdrs', $q);
        $this->db->or_like('tgl', $q);
        $this->db->or_like('cara_bayar', $q);
        $this->db->or_like('rj', $q);
        $this->db->or_like('ri', $q);
        $this->db->or_like('igd', $q);
        $this->db->or_like('sync', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idkunjungan', $q);
        $this->db->or_like('kdrs', $q);
        $this->db->or_like('tgl', $q);
        $this->db->or_like('cara_bayar', $q);
        $this->db->or_like('rj', $q);
        $this->db->or_like('ri', $q);
        $this->db->or_like('igd', $q);
        $this->db->or_like('sync', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file T_kunjungan_model.php */
/* Location: ./application/models/T_kunjungan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-08-05 18:01:12 */
/* http://harviacode.com */
