<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_pendapatan_model extends CI_Model
{

    public $table = 't_pendapatan';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('kdrs', $q);
	$this->db->or_like('cara_bayar', $q);
	$this->db->or_like('lunas', $q);
	$this->db->or_like('hutang', $q);
	$this->db->or_like('tgl', $q);
	$this->db->or_like('sycn', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('kdrs', $q);
	$this->db->or_like('cara_bayar', $q);
	$this->db->or_like('lunas', $q);
	$this->db->or_like('hutang', $q);
	$this->db->or_like('tgl', $q);
	$this->db->or_like('sycn', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file T_pendapatan_model.php */
/* Location: ./application/models/T_pendapatan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-08-06 04:29:25 */
/* http://harviacode.com */